site_name: NilBridge
copyright: Copyright &copy; 2020 - 2021 XBridgeX
theme:
    name: material
    language: zh
    logo: img/favicon.svg
    favicon: img/logo.png
    features:
        - search.highlight
        - seach.suggest
    plugins:
      - search:
          separator: '[\s\-\.]'

extra:
  generator: false

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details


nav:
  - HOME: index.md
  - 文件: file.md
  - 命令: cmd.md 
  - API: API.md
  - 正则表达式: regex.md
  - 常见问题: QandA.md
  - 更新日志: update.md
  - 开源协议: LIC.md
  - 支持项目: auspice.md
